apiVersion: v1
kind: Pod
metadata:
  name: web
  labels:
    app: web
spec:
  initContainers:
   - name: init-container
     image: busybox:1.32.0
     command: ['sh', '-c', 'wget -O- https://tinyurl.com/otus-k8s-intro | sh']
     volumeMounts:
       - name: app
         mountPath: /app
  containers:
  - name: web
    image: xdrjnbuofr/otus_nginx:1.0.0
    readinessProbe:
    volumeMounts:
      - name: app
        mountPath: /app

  volumes:
    - name: app
      emptyDir: {}
